### ISSUE TITLE
add docker command

### ISSUE THREAD

**Issue by x0rld** [bouk/babelfish#13]
the idea is really nice, you could add this command
 `docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:alpine go build -v -o babelfish`
 to build it inside a docker for people who don't use go in general

**Comment by x0rld** [comment]
you will add it or something ?

**Comment by bouk** [comment]
Woops sorry I didn't leave a commit—no I'm not going to add it
