### ISSUE TITLE
Error in translating export path

### ISSUE THREAD

**Issue by happysalada** [bouk/babelfish#15]
it seems that the following command 
`export PATH="$PATH:$HOME/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin"`
it translated to 
`set PATH $PATH "/Users/raphael/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin"`
which does not work in fish 3.3.0 anymore it seems.

this is coming from a file where the verbatim translation is 
`set -gx PATH "$HOME"'/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin'`
(this is the babelfish output)
I can't find the exact original bash line, it's a version where I tried to replace things. I'm hoping that the problem will be obvious enough.
Let me know if I can do anything else.

**Comment by bouk** [comment]
Why does it not work any more? What changed?

**Comment by happysalada** [comment]
this stopped working after fish was upgraded to 3.3.0 from 3.2.2

**Comment by bouk** [comment]
What exactly stopped working though? What is different from before?

**Comment by happysalada** [comment]
This line
`set -gx PATH "$HOME"'/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin'` generated by babel-fish , will cause the following output when run in fish
```
set: Warning: $PATH entry "/Users/raphael/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin" is not valid (No such file or directory)
set: Did you mean 'set PATH $PATH /run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin'?
```

**Comment by bouk** [comment]
This seems to have been fixed already: https://github.com/fish-shell/fish-shell/issues/8095

So hopefully fish 3.3.1 should be fine!

**Comment by happysalada** [comment]
Amazing! Thank you!
