### ISSUE TITLE
`$var#...` in argument lists is converted incorrectly

### ISSUE THREAD

**Issue by emilazy** [bouk/babelfish#23]
```
emily@yuyuko ~> cat test.bash
flake=nixpkgs
nix run $flake#hello
emily@yuyuko ~> bash test.bash
Hello, world!
emily@yuyuko ~> babelfish <test.bash
set flake 'nixpkgs'
#hello
nix run $flake
```

**Comment by emilazy** [comment]
Oops, hit the submit button too early. This came up when translating [nix-index's `command-not-found.sh` script](https://github.com/bennofs/nix-index/blob/a8ceb75b5f447ef5d0d5569dfd19401624b6c604/command-not-found.sh). And yes Nix's use of `#` as a separator is maybe not the best idea in the world, but we're stuck with it now and this is valid syntax :(

**Comment by bouk** [comment]
I've pushed v1.2.0, can you check whether this solves it?

**Comment by emilazy** [comment]
Having issues getting it to build with Nix due to `go: inconsistent vendoring`; are you sure the Go module files are up to date?

**Comment by bouk** [comment]
Had to fix one more thing, I've created a nixpkgs PR here: https://github.com/NixOS/nixpkgs/pull/239007

**Comment by emilazy** [comment]
Finally got around to testing this and it works now; thanks!
