### ISSUE TITLE
Additional empty line after pipeline via string collect -N

### ISSUE THREAD

**Issue by vothanhkiet** [bouk/babelfish#4]
Input: `APP_VERSION="v$(jq -r \'.version\'  ./package.json)-local"`
Translated: `set APP_VERSION 'v'(jq -r \'.version\' ./package.json | string collect -N; or echo)'-local'`

Output: 
```
v1.x.x
-local
```
Expected: `v1.x.x-local`

`string collect -N` emit one more empty line, this can be removed with `awk NF`, for example: `set APP_VERSION 'v'(jq -r '.version' ./package.json | string collect -N | awk NF; or echo)'-local'`

**Comment by bouk** [comment]
I think the -N flag is not needed.

**Comment by vothanhkiet** [comment]
Yes, remove -N will work, if you don't need it for specific reason
